/**
 * ID field type builder
 *
 * @remarks
 * Provides auto-generated ID field for unique identifiers.
 * IDs are typically auto-generated and not provided by users.
 */

import { BaseFieldBuilder, type BaseFieldConfig } from './base';

/**
 * ID field configuration
 */
export interface IdFieldConfig extends BaseFieldConfig {
  type: 'id';
  prefix?: string;
  autoGenerate: boolean;
}

/**
 * ID field builder
 *
 * @remarks
 * Implements fluent API for defining ID fields.
 * IDs are auto-generated by default and use format: prefix_randomString
 *
 * @example
 * ```typescript
 * // Basic ID (auto-generated)
 * const id = a.id();
 *
 * // ID with prefix
 * const userId = a.id().prefix('user'); // Generates: user_abc123xyz
 *
 * // ID with custom prefix
 * const orderId = a.id().prefix('order'); // Generates: order_abc123xyz
 * ```
 */
export class IdFieldBuilder extends BaseFieldBuilder<string, IdFieldConfig> {
  constructor() {
    super('id');
    this.config.autoGenerate = true;
  }

  /**
   * Set ID prefix
   *
   * @remarks
   * Adds a prefix to auto-generated IDs for better readability.
   * Format: {prefix}_{randomString}
   *
   * @example
   * ```typescript
   * const userId = a.id().prefix('user'); // user_abc123
   * const projectId = a.id().prefix('proj'); // proj_xyz789
   * ```
   *
   * @param value - Prefix string (typically 3-6 characters)
   */
  prefix(value: string): this {
    this.config.prefix = value;
    return this;
  }

  /**
   * Disable auto-generation (allow manual IDs)
   *
   * @remarks
   * By default, IDs are auto-generated. Use this to allow manual ID assignment.
   * Useful when importing data from external systems.
   *
   * @example
   * ```typescript
   * const externalId = a.id().manual().required();
   * ```
   */
  manual(): this {
    this.config.autoGenerate = false;
    return this;
  }
}
