/**
 * API Synthesizer Type Definitions
 *
 * Defines interfaces and types for the ApiSynthesizer that generates
 * Azure API Management resources and operations from schema definitions.
 *
 * @module @atakora/component/synthesis/api-synthesizer-types
 */

import type { SchemaObject } from '../schema/types';
import type { IService, IServiceApi } from '@atakora/cdk/apimanagement';
import type { IRestOperation } from '@atakora/lib/apimanagement/rest';
import type { IDatabaseAccount, ICosmosDBDatabase } from '@atakora/cdk/documentdb';
import type { IStorageAccount } from '@atakora/cdk/storage';
import type { ISite } from '@atakora/cdk/web';

// ============================================================================
// API Synthesizer Interface
// ============================================================================

/**
 * Interface for API Synthesizer
 *
 * @remarks
 * The ApiSynthesizer generates Azure API Management resources from schema definitions.
 * It follows Amplify's approach of creating REST operations for each CRUD model:
 * - GET /users (list)
 * - POST /users (create)
 * - GET /users/{id} (get)
 * - PUT /users/{id} (update)
 * - DELETE /users/{id} (delete)
 *
 * The synthesizer orchestrates:
 * 1. API Management service creation (APIM instance)
 * 2. API creation (logical grouping within APIM)
 * 3. Operation generation (CRUD operations per model)
 * 4. Policy application (auth, rate limiting, CORS)
 *
 * @example
 * ```typescript
 * const synthesizer = new ApiSynthesizer();
 * const resources = await synthesizer.synthesize(
 *   schema,
 *   resourceGroup,
 *   dataResources
 * );
 *
 * // Access generated resources
 * console.log(resources.apim.serviceName);
 * console.log(resources.operations.length); // 5 per CRUD model
 * ```
 */
export interface ApiSynthesizer {
  /**
   * Synthesize API Management resources from schema
   *
   * @param schema - Schema object containing model definitions
   * @param stack - Resource group stack for CDK construct placement
   * @param dataResources - Backend resources (Cosmos, Function App, Storage) for API integration
   * @returns Promise resolving to generated API resources
   *
   * @throws {Error} If schema validation fails
   * @throws {Error} If APIM configuration is invalid
   * @throws {Error} If operation generation fails
   *
   * @remarks
   * The synthesize method performs the following phases:
   * 1. **Discovery**: Analyze schema to identify CRUD models
   * 2. **APIM Setup**: Create or reference API Management service
   * 3. **API Creation**: Create API within APIM
   * 4. **Operation Generation**: Generate CRUD operations for each model
   * 5. **Policy Application**: Apply authentication and rate limiting policies
   * 6. **Validation**: Ensure all resources are valid and deployable
   */
  synthesize(
    schema: SchemaObject,
    stack: ResourceGroupStack,
    dataResources: BackendDataResources
  ): Promise<ApiResources>;
}

// ============================================================================
// Resource Stack Type
// ============================================================================

/**
 * Resource Group Stack
 *
 * @remarks
 * Represents a CDK stack scoped to a resource group.
 * This is a placeholder - the actual type will come from @atakora/cdk.
 * Using `any` for now to avoid circular dependencies during initial implementation.
 *
 * @todo Import from @atakora/cdk once ResourceGroupStack is implemented
 */
export type ResourceGroupStack = any;

// ============================================================================
// API Resources
// ============================================================================

/**
 * Generated API resources
 *
 * @remarks
 * Contains all Azure API Management resources generated by the synthesizer:
 * - **apim**: The API Management service instance
 * - **api**: The API within APIM (logical grouping of operations)
 * - **operations**: All CRUD operations generated for models
 *
 * Each CRUD model generates 5 operations following REST conventions.
 *
 * **Null Values:**
 * Properties may be null to support placeholder implementations during
 * incremental development. Consumers should check for null before using.
 *
 * @example
 * ```typescript
 * const resources: ApiResources = {
 *   apim: apimService,
 *   api: backendApi,
 *   operations: [
 *     { operationId: 'listUsers', method: 'GET', path: '/users', ... },
 *     { operationId: 'createUser', method: 'POST', path: '/users', ... },
 *     { operationId: 'getUser', method: 'GET', path: '/users/{id}', ... },
 *     { operationId: 'updateUser', method: 'PUT', path: '/users/{id}', ... },
 *     { operationId: 'deleteUser', method: 'DELETE', path: '/users/{id}', ... },
 *   ]
 * };
 * ```
 */
export interface ApiResources {
  /**
   * API Management service instance
   *
   * @remarks
   * The top-level Azure API Management service that hosts all APIs and operations.
   * This is the CDK construct reference (IService interface).
   *
   * **Null in Placeholder Implementations:**
   * May be null during incremental development phases. Check before using.
   */
  readonly apim: IService | null;

  /**
   * API within APIM
   *
   * @remarks
   * Logical grouping of operations within the API Management service.
   * Typically one API per backend application.
   *
   * **Null in Placeholder Implementations:**
   * May be null during incremental development phases. Check before using.
   */
  readonly api: IServiceApi | null;

  /**
   * Generated API operations
   *
   * @remarks
   * Array of all CRUD operations generated for schema models.
   * Each operation includes method, path, policies, and backend configuration.
   */
  readonly operations: readonly ApiOperation[];
}

// ============================================================================
// Data Resources (for backend integration)
// ============================================================================

/**
 * Backend data layer resources for API integration
 *
 * @remarks
 * Contains references to ALL backend resources (data storage, compute, and storage)
 * that APIs will integrate with. This is broader than {@link DataResources} from
 * data-synthesizer-types.ts which only contains Cosmos DB resources.
 *
 * These resources are typically generated by multiple synthesizers:
 * - DataSynthesizer: Cosmos DB account and database
 * - ComputeSynthesizer: Function App
 * - StorageSynthesizer: Storage Account
 *
 * The ApiSynthesizer receives these resources to configure backend URLs,
 * connection strings, and integration policies.
 *
 * @see {@link DataResources} from data-synthesizer-types.ts for Cosmos-only resources
 *
 * @example
 * ```typescript
 * const backendResources: BackendDataResources = {
 *   cosmosAccount: cosmosDbAccount,
 *   cosmosDatabase: cosmosDb,
 *   functionApp: functionAppService,
 *   storageAccount: storageAccount
 * };
 * ```
 */
export interface BackendDataResources {
  /**
   * Cosmos DB account
   *
   * @remarks
   * Reference to the Cosmos DB account for CRUD model storage.
   * Used to configure connection strings and backend integration.
   */
  readonly cosmosAccount?: IDatabaseAccount;

  /**
   * Cosmos DB database
   *
   * @remarks
   * Reference to the Cosmos DB database containing model containers.
   */
  readonly cosmosDatabase?: ICosmosDBDatabase;

  /**
   * Function App service
   *
   * @remarks
   * Reference to the Azure Function App that implements API logic.
   * The API Management operations will proxy to this Function App.
   */
  readonly functionApp?: ISite;

  /**
   * Storage Account
   *
   * @remarks
   * Reference to the Azure Storage Account for blob storage, queues, etc.
   */
  readonly storageAccount?: IStorageAccount;
}

// ============================================================================
// API Configuration
// ============================================================================

/**
 * API Management service configuration
 *
 * @remarks
 * Configuration for the Azure API Management service instance.
 * Provides sensible defaults for common scenarios while allowing customization.
 *
 * **Default Behavior:**
 * - SKU: Developer (non-prod), Consumption (production)
 * - Publisher: Derived from backend settings
 * - Location: Same as resource group
 *
 * @example
 * ```typescript
 * const config: ApiConfiguration = {
 *   serviceName: 'apim-myapp-dev-eus-01',
 *   sku: 'Developer',
 *   publisherEmail: 'api@example.com',
 *   publisherName: 'My Company'
 * };
 * ```
 */
export interface ApiConfiguration {
  /**
   * API Management service name
   *
   * @remarks
   * Must be globally unique across Azure.
   * If not provided, will be auto-generated using naming conventions.
   *
   * **Format**: `apim-{org}-{project}-{env}-{geo}-{instance}`
   *
   * **Constraints:**
   * - 1-50 characters
   * - Alphanumeric and hyphens only
   * - Must start with letter
   * - Must end with alphanumeric
   */
  readonly serviceName?: string;

  /**
   * API Management SKU
   *
   * @remarks
   * **SKU Options:**
   * - **Consumption**: Pay-per-use, serverless, no SLA
   * - **Developer**: Development/test, no SLA, single region
   * - **Basic**: Production workloads, 99.95% SLA, 2 units max
   * - **Standard**: Production workloads, 99.95% SLA, 4 units max
   * - **Premium**: Enterprise workloads, 99.99% SLA, multi-region
   *
   * **Default**: Developer (non-prod), Consumption (production)
   */
  readonly sku?: 'Consumption' | 'Developer' | 'Basic' | 'Standard' | 'Premium';

  /**
   * Publisher email address
   *
   * @remarks
   * Required for API Management service creation.
   * Used for notifications and developer portal communication.
   *
   * **Default**: Derived from backend settings or 'noreply@{domain}'
   */
  readonly publisherEmail?: string;

  /**
   * Publisher name/organization
   *
   * @remarks
   * Displayed in developer portal and API documentation.
   *
   * **Default**: Derived from backend settings organization name
   */
  readonly publisherName?: string;

  /**
   * Enable virtual network integration
   *
   * @remarks
   * Only available for Developer, Premium SKUs.
   * Required for private API endpoints.
   *
   * **Default**: false
   */
  readonly enableVNet?: boolean;

  /**
   * Virtual network type
   *
   * @remarks
   * - **External**: Public IP with VNet-integrated backend
   * - **Internal**: Private IP accessible only within VNet
   *
   * Only applicable if enableVNet is true.
   *
   * **Default**: 'External'
   */
  readonly vnetType?: 'External' | 'Internal';
}

// ============================================================================
// API Operation
// ============================================================================

/**
 * API operation definition
 *
 * @remarks
 * Represents a single REST API operation in Azure API Management.
 * Each CRUD model generates 5 operations following REST conventions.
 *
 * **CRUD Operations Pattern:**
 * - **List**: GET /resources
 * - **Create**: POST /resources
 * - **Get**: GET /resources/{id}
 * - **Update**: PUT /resources/{id}
 * - **Delete**: DELETE /resources/{id}
 *
 * @example
 * ```typescript
 * const operation: ApiOperation = {
 *   operationId: 'getUser',
 *   method: 'GET',
 *   path: '/users/{id}',
 *   displayName: 'Get User by ID',
 *   description: 'Retrieve a single user by their unique identifier',
 *   policies: {
 *     authentication: {
 *       type: 'jwt',
 *       config: { issuer: 'https://login.microsoft.com', ... }
 *     },
 *     rateLimit: {
 *       calls: 100,
 *       renewalPeriod: 60
 *     }
 *   }
 * };
 * ```
 */
export interface ApiOperation {
  /**
   * Unique operation identifier
   *
   * @remarks
   * Used for operation lookup and OpenAPI operationId.
   *
   * **Naming Convention**: `{verb}{ModelName}`
   * - Examples: `listUsers`, `createUser`, `getUser`, `updateUser`, `deleteUser`
   */
  readonly operationId: string;

  /**
   * HTTP method
   *
   * @remarks
   * Standard REST HTTP methods aligned with CRUD operations:
   * - **GET**: Retrieve (list or get)
   * - **POST**: Create
   * - **PUT**: Update (full replacement)
   * - **PATCH**: Update (partial)
   * - **DELETE**: Delete
   */
  readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

  /**
   * URL path template
   *
   * @remarks
   * Path may include template parameters in curly braces.
   *
   * **Examples:**
   * - `/users` (collection)
   * - `/users/{id}` (single resource)
   * - `/users/{userId}/posts/{postId}` (nested resource)
   */
  readonly path: string;

  /**
   * Human-readable operation name
   *
   * @remarks
   * Displayed in developer portal and API documentation.
   *
   * **Examples:**
   * - "List Users"
   * - "Create User"
   * - "Get User by ID"
   */
  readonly displayName: string;

  /**
   * Detailed operation description
   *
   * @remarks
   * Optional. Used for API documentation and developer portal.
   * Should explain the operation's purpose, parameters, and behavior.
   */
  readonly description?: string;

  /**
   * Operation policies
   *
   * @remarks
   * Defines authentication, rate limiting, CORS, and other policies
   * specific to this operation. If not specified, API-level or
   * service-level policies apply.
   */
  readonly policies?: PolicyConfiguration;

  /**
   * Backend service URL
   *
   * @remarks
   * The URL to which API Management will proxy requests.
   * Typically points to an Azure Function App endpoint.
   *
   * **Example**: `https://func-myapp-dev-eus-01.azurewebsites.net/api/{path}`
   */
  readonly backendUrl?: string;

  /**
   * Full REST operation definition
   *
   * @remarks
   * Optional reference to the complete IRestOperation for advanced scenarios
   * like OpenAPI generation. The synthesizer can use this for detailed
   * operation metadata, request/response schemas, etc.
   */
  readonly restOperation?: IRestOperation;
}

// ============================================================================
// Policy Configuration
// ============================================================================

/**
 * API operation policy configuration
 *
 * @remarks
 * Defines policies applied to API operations including authentication,
 * rate limiting, and CORS. Policies are implemented as Azure API Management
 * policy XML snippets.
 *
 * **Policy Scope:**
 * - Service-level: Applied to all APIs
 * - API-level: Applied to all operations in an API
 * - Operation-level: Applied to a single operation
 *
 * Operation-level policies override API-level, which override service-level.
 *
 * @example
 * ```typescript
 * const policies: PolicyConfiguration = {
 *   authentication: {
 *     type: 'jwt',
 *     config: {
 *       issuer: 'https://login.microsoftonline.com/{tenantId}',
 *       audience: 'api://my-api'
 *     }
 *   },
 *   rateLimit: {
 *     calls: 100,
 *     renewalPeriod: 60
 *   },
 *   cors: {
 *     allowedOrigins: ['https://app.example.com'],
 *     allowedMethods: ['GET', 'POST', 'PUT', 'DELETE']
 *   }
 * };
 * ```
 */
export interface PolicyConfiguration {
  /**
   * Rate limiting policy
   *
   * @remarks
   * Limits the number of API calls within a time window.
   * Prevents abuse and ensures fair usage.
   *
   * **Implementation**: Uses API Management `rate-limit` policy
   */
  readonly rateLimit?: RateLimitPolicy;

  /**
   * Authentication policy
   *
   * @remarks
   * Validates authentication tokens before allowing API access.
   * Supports multiple authentication schemes.
   */
  readonly authentication?: AuthenticationPolicy;

  /**
   * CORS policy
   *
   * @remarks
   * Configures Cross-Origin Resource Sharing for browser-based clients.
   * Required for web applications making API calls from different domains.
   */
  readonly cors?: CorsPolicy;

  /**
   * IP filtering policy
   *
   * @remarks
   * Restricts API access to specific IP addresses or ranges.
   * Useful for internal APIs or partner integrations.
   */
  readonly ipFilter?: IpFilterPolicy;

  /**
   * Caching policy
   *
   * @remarks
   * Configures response caching to improve performance and reduce backend load.
   * Only applicable to GET operations.
   */
  readonly caching?: CachingPolicy;

  /**
   * Custom XML policy
   *
   * @remarks
   * Raw API Management policy XML for advanced scenarios.
   * Use this for policies not covered by typed configuration.
   *
   * **Warning**: No type safety or validation. Use with caution.
   */
  readonly customXml?: string;
}

// ============================================================================
// Policy Type Definitions
// ============================================================================

/**
 * Rate limiting policy configuration
 *
 * @remarks
 * Controls the rate at which API calls can be made.
 * Prevents abuse and ensures service availability.
 *
 * @example
 * ```typescript
 * const rateLimit: RateLimitPolicy = {
 *   calls: 100,        // 100 calls
 *   renewalPeriod: 60  // per 60 seconds
 * };
 * ```
 */
export interface RateLimitPolicy {
  /**
   * Maximum number of calls allowed
   *
   * @remarks
   * Number of API calls permitted within the renewal period.
   */
  readonly calls: number;

  /**
   * Time window in seconds
   *
   * @remarks
   * Duration of the rate limit window in seconds.
   * After this period, the call counter resets.
   *
   * **Common Values:**
   * - 60 (1 minute)
   * - 3600 (1 hour)
   * - 86400 (1 day)
   */
  readonly renewalPeriod: number;

  /**
   * Counter key
   *
   * @remarks
   * Identifies the counter scope (per subscription, per IP, etc.)
   *
   * **Default**: Per subscription key
   */
  readonly counterKey?: string;
}

/**
 * Authentication policy configuration
 *
 * @remarks
 * Validates authentication tokens and enforces access control.
 * Supports multiple authentication schemes common in Azure.
 *
 * @example
 * OAuth2/JWT:
 * ```typescript
 * const auth: AuthenticationPolicy = {
 *   type: 'jwt',
 *   config: {
 *     issuer: 'https://login.microsoftonline.com/{tenantId}',
 *     audience: 'api://my-api',
 *     requiredClaims: ['scope']
 *   }
 * };
 * ```
 *
 * @example
 * API Key:
 * ```typescript
 * const auth: AuthenticationPolicy = {
 *   type: 'apiKey',
 *   config: {
 *     headerName: 'X-API-Key',
 *     paramName: 'api_key'
 *   }
 * };
 * ```
 */
export interface AuthenticationPolicy {
  /**
   * Authentication type
   *
   * @remarks
   * - **oauth2**: OAuth 2.0 / OpenID Connect
   * - **apiKey**: Subscription key or custom API key
   * - **jwt**: JWT token validation
   * - **certificate**: Client certificate authentication
   */
  readonly type: 'oauth2' | 'apiKey' | 'jwt' | 'certificate';

  /**
   * Type-specific configuration
   *
   * @remarks
   * Configuration schema varies by authentication type.
   * See specific type examples for structure.
   */
  readonly config: Record<string, any>;
}

/**
 * CORS policy configuration
 *
 * @remarks
 * Configures Cross-Origin Resource Sharing headers.
 * Required for browser-based single-page applications.
 *
 * @example
 * ```typescript
 * const cors: CorsPolicy = {
 *   allowedOrigins: ['https://app.example.com', 'https://admin.example.com'],
 *   allowedMethods: ['GET', 'POST', 'PUT', 'DELETE'],
 *   allowedHeaders: ['Content-Type', 'Authorization'],
 *   exposeHeaders: ['X-Request-Id'],
 *   allowCredentials: true,
 *   maxAge: 3600
 * };
 * ```
 */
export interface CorsPolicy {
  /**
   * Allowed origin domains
   *
   * @remarks
   * Array of allowed origins or '*' for all origins.
   *
   * **Security Warning**: Avoid using '*' in production.
   * Always specify explicit origins for security.
   *
   * **Examples:**
   * - `['https://app.example.com']`
   * - `['https://*.example.com']` (wildcard subdomain)
   */
  readonly allowedOrigins: readonly string[];

  /**
   * Allowed HTTP methods
   *
   * @remarks
   * Array of HTTP methods permitted for CORS requests.
   *
   * **Common**: `['GET', 'POST', 'PUT', 'DELETE', 'PATCH']`
   */
  readonly allowedMethods: readonly string[];

  /**
   * Allowed request headers
   *
   * @remarks
   * Headers that clients can include in CORS requests.
   *
   * **Common**: `['Content-Type', 'Authorization', 'X-Request-Id']`
   */
  readonly allowedHeaders?: readonly string[];

  /**
   * Exposed response headers
   *
   * @remarks
   * Headers that browsers can access in CORS responses.
   *
   * **Common**: `['X-Request-Id', 'X-Total-Count']`
   */
  readonly exposeHeaders?: readonly string[];

  /**
   * Allow credentials (cookies, auth headers)
   *
   * @remarks
   * If true, allows cookies and authentication headers in CORS requests.
   *
   * **Default**: false
   */
  readonly allowCredentials?: boolean;

  /**
   * Preflight cache duration in seconds
   *
   * @remarks
   * How long browsers should cache CORS preflight responses.
   *
   * **Default**: 3600 (1 hour)
   */
  readonly maxAge?: number;
}

/**
 * IP filtering policy configuration
 *
 * @remarks
 * Restricts API access based on client IP address.
 * Useful for internal APIs or partner integrations.
 *
 * @example
 * ```typescript
 * const ipFilter: IpFilterPolicy = {
 *   mode: 'allow',
 *   addresses: ['203.0.113.0/24', '198.51.100.42']
 * };
 * ```
 */
export interface IpFilterPolicy {
  /**
   * Filter mode
   *
   * @remarks
   * - **allow**: Only listed IPs can access (whitelist)
   * - **deny**: Listed IPs are blocked (blacklist)
   */
  readonly mode: 'allow' | 'deny';

  /**
   * IP addresses or CIDR ranges
   *
   * @remarks
   * Array of IP addresses or CIDR notation ranges.
   *
   * **Examples:**
   * - `'203.0.113.42'` (single IP)
   * - `'203.0.113.0/24'` (CIDR range)
   */
  readonly addresses: readonly string[];
}

/**
 * Caching policy configuration
 *
 * @remarks
 * Configures response caching for GET operations.
 * Improves performance and reduces backend load.
 *
 * **Note**: Only applicable to GET operations with successful responses (200-299).
 *
 * @example
 * ```typescript
 * const caching: CachingPolicy = {
 *   duration: 300,              // Cache for 5 minutes
 *   varyByHeaders: ['Accept'],  // Vary cache by Accept header
 *   varyByQueryParams: ['page'] // Vary cache by page param
 * };
 * ```
 */
export interface CachingPolicy {
  /**
   * Cache duration in seconds
   *
   * @remarks
   * How long responses should be cached.
   *
   * **Common Values:**
   * - 60 (1 minute)
   * - 300 (5 minutes)
   * - 3600 (1 hour)
   */
  readonly duration: number;

  /**
   * Vary cache by request headers
   *
   * @remarks
   * Cache separate responses for different header values.
   *
   * **Example**: `['Accept', 'Accept-Language']`
   */
  readonly varyByHeaders?: readonly string[];

  /**
   * Vary cache by query parameters
   *
   * @remarks
   * Cache separate responses for different query parameter values.
   *
   * **Example**: `['page', 'limit', 'sort']`
   */
  readonly varyByQueryParams?: readonly string[];

  /**
   * Cache responses per subscription
   *
   * @remarks
   * If true, each subscription gets its own cache.
   *
   * **Default**: false
   */
  readonly varyBySubscription?: boolean;
}
