/**
 * Function Synthesizer Type Definitions
 *
 * Defines interfaces and types for the FunctionSynthesizer that generates
 * Azure Functions resources and code from schema definitions.
 *
 * @module @atakora/component/synthesis/function-synthesizer-types
 */

import type { SchemaObject } from './data-synthesizer-types';
import type { DataResources } from './data-synthesizer-types';
import type { ApiResources } from './api-synthesizer-types';
import type { ResourceGroupStack } from '@atakora/lib';
import type { ISite } from '@atakora/cdk/web';
import type { IServerFarm } from '@atakora/cdk/web';

// ============================================================================
// Function Synthesizer Interface
// ============================================================================

/**
 * Interface for Function Synthesizer
 *
 * @remarks
 * The FunctionSynthesizer generates Azure Functions resources and code from schema definitions.
 * It creates serverless compute infrastructure and TypeScript function handlers for:
 * - CRUD operations for each model (5 functions per model: get, list, create, update, delete)
 * - Custom function models defined in the schema
 * - Event handlers for event models
 *
 * The synthesizer orchestrates:
 * 1. App Service Plan creation (hosting infrastructure)
 * 2. Function App creation (runtime environment)
 * 3. Function code generation (TypeScript handlers)
 * 4. Cosmos DB bindings configuration
 * 5. Application settings and environment variables
 *
 * @example
 * ```typescript
 * const synthesizer = new FunctionSynthesizer();
 * const resources = await synthesizer.synthesize(
 *   schema,
 *   stack,
 *   dataResources,
 *   apiResources
 * );
 *
 * // Access generated resources
 * console.log(resources.functionApp.siteName);
 * console.log(resources.functions.length); // 5 per CRUD model
 * ```
 */
export interface FunctionSynthesizer {
  /**
   * Synthesize Azure Functions resources from schema
   *
   * @param schema - Schema object containing model definitions
   * @param stack - Resource group stack for CDK construct placement
   * @param dataResources - Cosmos DB resources for data layer integration
   * @param apiResources - API Management resources for API layer integration
   * @returns Promise resolving to generated function resources
   *
   * @throws {Error} If schema validation fails
   * @throws {Error} If function app configuration is invalid
   * @throws {Error} If code generation fails
   *
   * @remarks
   * The synthesize method performs the following phases:
   * 1. **Discovery**: Analyze schema to identify CRUD models, function models, and event models
   * 2. **Infrastructure**: Create App Service Plan and Function App
   * 3. **Code Generation**: Generate TypeScript function handlers for each operation
   * 4. **Bindings**: Configure Cosmos DB input/output bindings
   * 5. **Configuration**: Set application settings, connection strings, and environment variables
   * 6. **Validation**: Ensure all resources and code are valid and deployable
   */
  synthesize(
    schema: SchemaObject,
    stack: ResourceGroupStack,
    dataResources: DataResources,
    apiResources: ApiResources
  ): Promise<FunctionResources>;
}

// ============================================================================
// Function Resources
// ============================================================================

/**
 * Generated Function resources
 *
 * @remarks
 * Contains all Azure Functions infrastructure and code artifacts generated by the synthesizer:
 * - **functionApp**: The Azure Function App (L2 CDK construct)
 * - **appServicePlan**: The App Service Plan hosting the Function App (L2 CDK construct)
 * - **functions**: Array of individual function definitions with metadata
 *
 * Each CRUD model generates 5 functions following REST conventions:
 * - GET /resources (list)
 * - POST /resources (create)
 * - GET /resources/{id} (get)
 * - PUT /resources/{id} (update)
 * - DELETE /resources/{id} (delete)
 *
 * @example
 * ```typescript
 * const resources: FunctionResources = {
 *   functionApp: functionAppSite,
 *   appServicePlan: plan,
 *   functions: [
 *     {
 *       name: 'list-users',
 *       type: 'list',
 *       modelName: 'User',
 *       httpTrigger: { methods: ['GET'], route: 'users', authLevel: 'function' },
 *       cosmosBinding: { connection: 'CosmosDB', databaseName: 'myapp', containerName: 'users' },
 *       template: { language: 'typescript', templateType: 'crud', sourceCode: '...' }
 *     },
 *     // ... 4 more functions for User model
 *   ]
 * };
 * ```
 */
export interface FunctionResources {
  /**
   * Function App resource (L2 construct)
   *
   * @remarks
   * The Azure Function App (Sites resource with kind 'functionapp') that hosts all function code.
   * Configured with runtime settings, app settings, and managed identity.
   *
   * **Null in Placeholder Implementations:**
   * May be null during incremental development phases. Check before using.
   *
   * Use this to:
   * - Grant access to other Azure resources (Cosmos DB, Storage, etc.)
   * - Get the function app URL for API integration
   * - Add additional app settings or connection strings
   * - Configure deployment settings
   *
   * This is the ISite interface from @atakora/cdk/web, representing a Function App
   * (which is technically a specialized App Service).
   */
  readonly functionApp: ISite | null;

  /**
   * App Service Plan resource (L2 construct)
   *
   * @remarks
   * The hosting plan for the Function App. Defines the compute resources,
   * scaling behavior, and pricing tier.
   *
   * **Null in Placeholder Implementations:**
   * May be null during incremental development phases. Check before using.
   *
   * **Common SKUs:**
   * - **Y1** (Consumption): Pay-per-execution, auto-scale, 1.5GB memory
   * - **EP1** (Elastic Premium): Pre-warmed instances, VNet integration, 3.5GB memory
   * - **EP2** (Elastic Premium): Pre-warmed instances, VNet integration, 7GB memory
   * - **EP3** (Elastic Premium): Pre-warmed instances, VNet integration, 14GB memory
   *
   * Use this to:
   * - Scale out instances
   * - Configure auto-scale rules
   * - Enable zone redundancy
   * - Reference in other Function Apps (shared plan)
   */
  readonly appServicePlan: IServerFarm | null;

  /**
   * Individual function definitions
   *
   * @remarks
   * Array of all functions generated for the schema, including:
   * - CRUD operation functions (5 per model)
   * - Custom function models
   * - Event handler functions
   *
   * Each definition includes:
   * - Function metadata (name, type, model)
   * - HTTP trigger configuration
   * - Cosmos DB bindings (if applicable)
   * - Generated TypeScript source code template
   *
   * Use this to:
   * - Generate function.json files during deployment
   * - Write function handler TypeScript files
   * - Configure routing and authorization
   * - Track function inventory for documentation
   *
   * The functions array is ordered by model name and operation type for consistency.
   */
  readonly functions: readonly FunctionDefinition[];
}

// ============================================================================
// Function Synthesis Options
// ============================================================================

/**
 * Options for function synthesis
 *
 * @remarks
 * Optional configuration for customizing function app creation.
 * All properties are optional and have sensible defaults.
 *
 * @example
 * ```typescript
 * const options: FunctionSynthesisOptions = {
 *   sku: 'EP1',
 *   alwaysOn: true,
 *   appSettings: {
 *     'NODE_ENV': 'production'
 *   }
 * };
 * ```
 */
export interface FunctionSynthesisOptions {
  /**
   * App Service Plan SKU (optional - defaults based on environment)
   *
   * @remarks
   * Determines the hosting plan and pricing tier.
   *
   * **SKU Options:**
   * - **Y1** (Consumption): Pay-per-execution, dynamic scaling, 1.5GB memory, 5-10 min timeout
   * - **EP1** (Elastic Premium): Always ready instances, VNet, 3.5GB memory, unlimited timeout
   * - **EP2** (Elastic Premium): Always ready instances, VNet, 7GB memory, unlimited timeout
   * - **EP3** (Elastic Premium): Always ready instances, VNet, 14GB memory, unlimited timeout
   *
   * **Default**: 'Y1' for development, 'EP1' for production
   */
  readonly sku?: 'Y1' | 'EP1' | 'EP2' | 'EP3';

  /**
   * Always On setting (optional - defaults based on SKU)
   *
   * @remarks
   * Keeps the Function App loaded even when idle.
   * Prevents cold starts but increases cost.
   *
   * **Constraints:**
   * - Must be false for Consumption (Y1) plans
   * - Recommended true for Premium (EP*) plans
   *
   * **Default**: false for Y1, true for EP*
   */
  readonly alwaysOn?: boolean;

  /**
   * Application settings (optional)
   *
   * @remarks
   * Environment variables and configuration settings for the Function App.
   * Merged with auto-generated settings (Cosmos DB connection strings, etc.).
   *
   * @example
   * ```typescript
   * appSettings: {
   *   'NODE_ENV': 'production',
   *   'LOG_LEVEL': 'info',
   *   'CUSTOM_API_KEY': '@Microsoft.KeyVault(SecretUri=...)'
   * }
   * ```
   */
  readonly appSettings?: Record<string, string>;
}

// ============================================================================
// Function Configuration
// ============================================================================

/**
 * Function App configuration
 *
 * @remarks
 * Configuration options for the Azure Function App.
 * Provides sensible defaults while allowing customization for different environments.
 *
 * **Default Behavior:**
 * - Runtime: Node.js (based on generated TypeScript code)
 * - Runtime Version: 18 (LTS)
 * - SKU: Y1 Consumption (development), EP1 (production)
 * - Always On: false (Consumption), true (Premium)
 *
 * @example
 * Development configuration:
 * ```typescript
 * const config: FunctionConfiguration = {
 *   appName: 'func-myapp-dev-eus-01',
 *   runtime: 'node',
 *   runtimeVersion: '18',
 *   sku: 'Y1',
 *   alwaysOn: false
 * };
 * ```
 *
 * @example
 * Production configuration with Premium plan:
 * ```typescript
 * const config: FunctionConfiguration = {
 *   appName: 'func-myapp-prod-eus-01',
 *   runtime: 'node',
 *   runtimeVersion: '18',
 *   sku: 'EP1',
 *   alwaysOn: true,
 *   appSettings: {
 *     'WEBSITE_RUN_FROM_PACKAGE': '1',
 *     'FUNCTIONS_WORKER_RUNTIME': 'node',
 *     'NODE_ENV': 'production'
 *   }
 * };
 * ```
 */
export interface FunctionConfiguration {
  /**
   * Function App name (optional - auto-generated if not provided)
   *
   * @remarks
   * Must be globally unique across all of Azure.
   *
   * **Constraints:**
   * - 2-60 characters
   * - Alphanumeric and hyphens only
   * - Cannot start or end with hyphen
   * - Globally unique (creates {appName}.azurewebsites.net)
   *
   * **Pattern**: `^[a-zA-Z0-9][a-zA-Z0-9-]{0,58}[a-zA-Z0-9]$`
   *
   * If not provided, a name will be generated using the project naming convention:
   * - Format: `func-{project}-{env}-{geo}-{instance}`
   * - Example: `func-myapp-dev-eus-01`
   */
  readonly appName?: string;

  /**
   * Function runtime (optional - defaults to 'node')
   *
   * @remarks
   * The language runtime for Azure Functions.
   *
   * **Supported Runtimes:**
   * - **node**: Node.js (for TypeScript/JavaScript)
   * - **python**: Python
   * - **dotnet**: .NET (C#/F#)
   *
   * **Default**: 'node' (since we generate TypeScript code)
   */
  readonly runtime?: 'node' | 'python' | 'dotnet';

  /**
   * Runtime version (optional - defaults based on runtime)
   *
   * @remarks
   * The version of the runtime to use.
   *
   * **Node.js versions:**
   * - '18' (LTS, recommended)
   * - '16' (LTS)
   * - '14' (legacy)
   *
   * **Python versions:**
   * - '3.11'
   * - '3.10'
   * - '3.9'
   *
   * **.NET versions:**
   * - '8.0' (LTS)
   * - '6.0' (LTS)
   *
   * **Default**: '18' for node, '3.11' for python, '8.0' for dotnet
   */
  readonly runtimeVersion?: string;

  /**
   * App Service Plan SKU (optional - defaults based on environment)
   *
   * @remarks
   * Determines the hosting plan and pricing tier.
   *
   * **SKU Options:**
   * - **Y1** (Consumption): Pay-per-execution, dynamic scaling, 1.5GB memory, 5-10 min timeout
   * - **EP1** (Elastic Premium): Always ready instances, VNet, 3.5GB memory, unlimited timeout
   * - **EP2** (Elastic Premium): Always ready instances, VNet, 7GB memory, unlimited timeout
   * - **EP3** (Elastic Premium): Always ready instances, VNet, 14GB memory, unlimited timeout
   *
   * **Default**: 'Y1' for development, 'EP1' for production
   *
   * **Note**: Consumption (Y1) cannot use alwaysOn=true. Premium plans (EP*) support VNet integration.
   */
  readonly sku?: 'Y1' | 'EP1' | 'EP2' | 'EP3';

  /**
   * Always On setting (optional - defaults based on SKU)
   *
   * @remarks
   * Keeps the Function App loaded even when idle.
   * Prevents cold starts but increases cost.
   *
   * **Constraints:**
   * - Must be false for Consumption (Y1) plans
   * - Recommended true for Premium (EP*) plans
   * - Recommended true for production workloads on Premium plans
   *
   * **Default**: false for Y1, true for EP*
   */
  readonly alwaysOn?: boolean;

  /**
   * Application settings (optional)
   *
   * @remarks
   * Environment variables and configuration settings for the Function App.
   * Merged with auto-generated settings (Cosmos DB connection strings, etc.).
   *
   * **Common Settings:**
   * - `WEBSITE_RUN_FROM_PACKAGE`: '1' (run from deployment package)
   * - `FUNCTIONS_WORKER_RUNTIME`: Runtime identifier
   * - `NODE_ENV`: 'production' or 'development'
   * - `APPINSIGHTS_INSTRUMENTATIONKEY`: Application Insights key
   *
   * **Auto-generated Settings:**
   * - `CosmosDB__connectionString`: Cosmos DB connection string
   * - `CosmosDB__databaseName`: Database name
   * - `FUNCTIONS_EXTENSION_VERSION`: '~4'
   *
   * Custom settings override auto-generated settings with the same key.
   *
   * @example
   * ```typescript
   * appSettings: {
   *   'NODE_ENV': 'production',
   *   'LOG_LEVEL': 'info',
   *   'CUSTOM_API_KEY': '@Microsoft.KeyVault(SecretUri=...)'
   * }
   * ```
   */
  readonly appSettings?: Record<string, string>;
}

// ============================================================================
// Function Definition
// ============================================================================

/**
 * Individual function definition
 *
 * @remarks
 * Represents a single Azure Function with its configuration and generated code.
 * Each function includes HTTP trigger configuration, optional Cosmos DB bindings,
 * and a TypeScript code template.
 *
 * **Function Types:**
 * - **get**: Retrieve single resource by ID (GET /resources/{id})
 * - **list**: Retrieve collection of resources (GET /resources)
 * - **create**: Create new resource (POST /resources)
 * - **update**: Update existing resource (PUT /resources/{id})
 * - **delete**: Delete resource (DELETE /resources/{id})
 * - **custom**: Custom function logic (defined in schema)
 *
 * @example
 * CRUD function for User model:
 * ```typescript
 * const func: FunctionDefinition = {
 *   name: 'get-user',
 *   type: 'get',
 *   modelName: 'User',
 *   httpTrigger: {
 *     methods: ['GET'],
 *     route: 'users/{id}',
 *     authLevel: 'function'
 *   },
 *   cosmosBinding: {
 *     connection: 'CosmosDB',
 *     databaseName: 'myapp',
 *     containerName: 'users'
 *   },
 *   template: {
 *     language: 'typescript',
 *     templateType: 'crud',
 *     sourceCode: 'export async function handler(...) { ... }',
 *     dependencies: {
 *       '@azure/cosmos': '^4.0.0'
 *     }
 *   }
 * };
 * ```
 */
export interface FunctionDefinition {
  /**
   * Function name
   *
   * @remarks
   * Unique identifier for the function. Used for:
   * - Function folder name (e.g., `functions/get-user/`)
   * - Function.json file location
   * - Logging and telemetry
   * - Azure portal display name
   *
   * **Naming Convention**: `{operation}-{model-name}`
   * - Examples: `get-user`, `list-products`, `create-order`, `update-invoice`, `delete-comment`
   *
   * **Constraints:**
   * - Lowercase letters, numbers, and hyphens only
   * - Must be unique within the Function App
   * - Recommended: 2-50 characters
   */
  readonly name: string;

  /**
   * Function type/operation
   *
   * @remarks
   * Indicates the operation this function performs.
   * Determines the HTTP method, route pattern, and code template.
   *
   * **CRUD Types:**
   * - **get**: Retrieve single resource by ID
   * - **list**: Retrieve collection of resources
   * - **create**: Create new resource
   * - **update**: Update existing resource
   * - **delete**: Delete resource
   *
   * **Custom Type:**
   * - **custom**: Custom logic defined in schema function models
   */
  readonly type: 'get' | 'list' | 'create' | 'update' | 'delete' | 'custom';

  /**
   * Associated model name
   *
   * @remarks
   * The schema model this function operates on.
   * For CRUD operations, this is the CRUD model name (e.g., 'User', 'Product').
   * For custom functions, this may be a descriptive name.
   *
   * Used for:
   * - Determining Cosmos DB container name
   * - Generating function code
   * - API documentation
   *
   * **Example**: 'User', 'Product', 'Order', 'Invoice'
   */
  readonly modelName: string;

  /**
   * HTTP trigger configuration
   *
   * @remarks
   * Defines how the function is triggered via HTTP requests.
   * Includes allowed methods, route pattern, and authorization level.
   *
   * **Route Patterns:**
   * - Collection: `users` (for list, create)
   * - Resource: `users/{id}` (for get, update, delete)
   * - Nested: `users/{userId}/posts/{postId}`
   *
   * **Auth Levels:**
   * - **anonymous**: No authentication required (not recommended)
   * - **function**: Requires function key in query string or header
   * - **admin**: Requires master key (host-level access)
   *
   * For production, use 'function' level and delegate authentication to API Management.
   */
  readonly httpTrigger: HttpTriggerConfig;

  /**
   * Cosmos DB binding configuration (optional)
   *
   * @remarks
   * Configures input/output bindings to Cosmos DB for data access.
   * Only applicable to CRUD functions that interact with Cosmos DB.
   *
   * Custom functions may not have Cosmos DB bindings if they don't access data.
   *
   * **Binding Modes:**
   * - Input binding: Read documents (for get, list)
   * - Output binding: Write documents (for create, update, delete)
   *
   * The binding configuration is used to generate the `bindings` array in function.json.
   */
  readonly cosmosBinding?: CosmosBindingConfig;

  /**
   * Function code template
   *
   * @remarks
   * Contains the generated TypeScript source code for the function handler.
   * Includes imports, handler function, and business logic.
   *
   * The template is rendered during synthesis and written to the function's
   * index.ts file in the deployment package.
   *
   * **Template Types:**
   * - **crud**: Standard CRUD operation template (get, list, create, update, delete)
   * - **custom**: Custom logic template for function models
   *
   * Templates include error handling, logging, and Cosmos DB client initialization.
   */
  readonly template: FunctionTemplate;
}

// ============================================================================
// HTTP Trigger Configuration
// ============================================================================

/**
 * HTTP trigger configuration for Azure Functions
 *
 * @remarks
 * Defines how a function responds to HTTP requests.
 * Maps to the HTTP trigger binding in function.json.
 *
 * @example
 * GET endpoint:
 * ```typescript
 * const trigger: HttpTriggerConfig = {
 *   methods: ['GET'],
 *   route: 'users/{id}',
 *   authLevel: 'function'
 * };
 * ```
 *
 * @example
 * POST endpoint:
 * ```typescript
 * const trigger: HttpTriggerConfig = {
 *   methods: ['POST'],
 *   route: 'users',
 *   authLevel: 'function'
 * };
 * ```
 */
export interface HttpTriggerConfig {
  /**
   * Allowed HTTP methods
   *
   * @remarks
   * Array of HTTP methods that can trigger this function.
   * Functions typically accept a single method, but multiple methods are supported.
   *
   * **Standard CRUD Mapping:**
   * - GET: Retrieve (get, list)
   * - POST: Create
   * - PUT: Update (full replacement)
   * - PATCH: Update (partial)
   * - DELETE: Delete
   *
   * **Examples:**
   * - `['GET']` - Read-only endpoint
   * - `['POST']` - Create endpoint
   * - `['PUT', 'PATCH']` - Update endpoint supporting both methods
   */
  readonly methods: readonly ('GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH')[];

  /**
   * URL route pattern
   *
   * @remarks
   * The route template for the function endpoint.
   * Relative to the Function App base URL.
   *
   * **Route Parameters:**
   * - Enclosed in curly braces: `{paramName}`
   * - Accessible in function code via `context.bindingData.paramName`
   * - Can include multiple parameters: `users/{userId}/posts/{postId}`
   *
   * **Examples:**
   * - `users` - Collection endpoint
   * - `users/{id}` - Resource endpoint with ID parameter
   * - `users/{userId}/orders/{orderId}` - Nested resource
   *
   * **Note**: Do not include leading slash. Azure Functions adds it automatically.
   */
  readonly route: string;

  /**
   * Authorization level
   *
   * @remarks
   * Determines what level of authentication is required to invoke the function.
   *
   * **Levels:**
   * - **anonymous**: No key required (public endpoint)
   * - **function**: Function-specific key required
   * - **admin**: Master (host) key required
   *
   * **Recommendations:**
   * - Development: 'function' or 'anonymous' (for testing)
   * - Production: 'function' with API Management handling authentication
   * - Internal admin endpoints: 'admin'
   *
   * **Security Note**: 'anonymous' should only be used for truly public endpoints.
   * For production APIs, use 'function' level and delegate auth to API Management.
   *
   * @default 'function'
   */
  readonly authLevel?: 'anonymous' | 'function' | 'admin';
}

// ============================================================================
// Cosmos DB Binding Configuration
// ============================================================================

/**
 * Cosmos DB binding configuration for Azure Functions
 *
 * @remarks
 * Configures input/output bindings to Cosmos DB for data operations.
 * The binding allows functions to read and write documents without
 * explicitly managing the Cosmos DB client.
 *
 * **Binding Types:**
 * - **Input Binding**: Read documents (for get, list operations)
 * - **Output Binding**: Write documents (for create, update, delete operations)
 *
 * The binding direction is inferred from the function type:
 * - get, list → input binding
 * - create, update, delete → output binding
 *
 * @example
 * Input binding for get operation:
 * ```typescript
 * const binding: CosmosBindingConfig = {
 *   connection: 'CosmosDB',
 *   databaseName: 'myapp',
 *   containerName: 'users'
 * };
 * ```
 *
 * Generates function.json:
 * ```json
 * {
 *   "type": "cosmosDB",
 *   "direction": "in",
 *   "name": "inputDocument",
 *   "connectionStringSetting": "CosmosDB",
 *   "databaseName": "myapp",
 *   "collectionName": "users",
 *   "id": "{id}",
 *   "partitionKey": "{id}"
 * }
 * ```
 */
export interface CosmosBindingConfig {
  /**
   * Connection string setting name
   *
   * @remarks
   * Name of the app setting containing the Cosmos DB connection string.
   * The Function App's application settings will have an entry like:
   * - `CosmosDB`: `AccountEndpoint=https://...;AccountKey=...;`
   *
   * **Convention**: Use 'CosmosDB' as the standard connection setting name.
   *
   * **Security**: Connection strings are stored as app settings (encrypted at rest).
   * For enhanced security, use Key Vault references:
   * - `@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/cosmos-connection)`
   *
   * @default 'CosmosDB'
   */
  readonly connection: string;

  /**
   * Cosmos DB database name
   *
   * @remarks
   * The name of the database containing the target container.
   * Typically matches the project or application name.
   *
   * **Example**: 'myapp', 'myapp-db', 'production-db'
   */
  readonly databaseName: string;

  /**
   * Cosmos DB container name
   *
   * @remarks
   * The name of the container (collection) to read from or write to.
   * Typically the pluralized, lowercase model name.
   *
   * **Naming Convention**: Pluralize and lowercase the model name
   * - Model 'User' → Container 'users'
   * - Model 'Product' → Container 'products'
   * - Model 'Order' → Container 'orders'
   *
   * **Example**: 'users', 'products', 'orders', 'invoices'
   */
  readonly containerName: string;
}

// ============================================================================
// Function Template
// ============================================================================

/**
 * Function code template
 *
 * @remarks
 * Contains the generated source code and metadata for a function.
 * Used during synthesis to create deployable function code.
 *
 * **Template Generation:**
 * 1. Synthesizer generates TypeScript code from templates
 * 2. Code includes imports, handler function, business logic
 * 3. Error handling and logging are built-in
 * 4. Dependencies are tracked for package.json generation
 *
 * **Deployment:**
 * - Source code is written to `functions/{functionName}/index.ts`
 * - Dependencies are aggregated into root `package.json`
 * - Code is compiled to JavaScript for deployment
 *
 * @example
 * CRUD template for get operation:
 * ```typescript
 * const template: FunctionTemplate = {
 *   language: 'typescript',
 *   templateType: 'crud',
 *   sourceCode: `
 *     import { AzureFunction, Context, HttpRequest } from '@azure/functions';
 *     import { CosmosClient } from '@azure/cosmos';
 *
 *     const handler: AzureFunction = async (context: Context, req: HttpRequest) => {
 *       const { id } = context.bindingData;
 *       const client = new CosmosClient(process.env.CosmosDB);
 *       const container = client.database('myapp').container('users');
 *       const { resource } = await container.item(id, id).read();
 *       context.res = { status: 200, body: resource };
 *     };
 *
 *     export default handler;
 *   `,
 *   dependencies: {
 *     '@azure/functions': '^4.0.0',
 *     '@azure/cosmos': '^4.0.0'
 *   }
 * };
 * ```
 */
export interface FunctionTemplate {
  /**
   * Programming language
   *
   * @remarks
   * The language of the generated code.
   *
   * **Supported Languages:**
   * - **typescript**: TypeScript (primary, recommended)
   * - **javascript**: JavaScript (for legacy support)
   *
   * **Default**: 'typescript'
   *
   * TypeScript is recommended for type safety, better IDE support,
   * and alignment with the component library's TypeScript-first approach.
   */
  readonly language: 'typescript' | 'javascript';

  /**
   * Template type
   *
   * @remarks
   * Indicates the template pattern used for code generation.
   *
   * **Template Types:**
   * - **crud**: Standard CRUD operation (get, list, create, update, delete)
   * - **custom**: Custom function logic from schema function models
   *
   * CRUD templates follow a standard pattern with error handling,
   * validation, and Cosmos DB integration.
   *
   * Custom templates are more flexible and may include different logic.
   */
  readonly templateType: 'crud' | 'custom';

  /**
   * Generated source code
   *
   * @remarks
   * The complete TypeScript or JavaScript source code for the function.
   * Includes:
   * - Import statements
   * - Handler function declaration
   * - Business logic (CRUD operations, custom logic)
   * - Error handling
   * - Logging statements
   * - Response formatting
   *
   * **Code Structure:**
   * ```typescript
   * // Imports
   * import { AzureFunction, Context, HttpRequest } from '@azure/functions';
   * import { CosmosClient } from '@azure/cosmos';
   *
   * // Handler
   * const handler: AzureFunction = async (context: Context, req: HttpRequest) => {
   *   // Business logic
   *   context.res = { status: 200, body: result };
   * };
   *
   * // Export
   * export default handler;
   * ```
   *
   * The source code is written to `functions/{functionName}/index.ts` during deployment.
   */
  readonly sourceCode: string;

  /**
   * npm package dependencies (optional)
   *
   * @remarks
   * Map of package names to version specifiers required by the function.
   * These dependencies are aggregated across all functions and written
   * to the root `package.json` of the deployment package.
   *
   * **Common Dependencies:**
   * - `@azure/functions`: Azure Functions runtime and types
   * - `@azure/cosmos`: Cosmos DB client SDK
   * - `@azure/identity`: Azure authentication
   * - `@azure/storage-blob`: Blob storage client
   * - `zod`: Runtime validation
   *
   * **Version Specifiers:**
   * - Exact: `'4.0.0'`
   * - Caret: `'^4.0.0'` (recommended, allows patch/minor updates)
   * - Tilde: `'~4.0.0'` (allows patch updates only)
   *
   * @example
   * ```typescript
   * dependencies: {
   *   '@azure/functions': '^4.0.0',
   *   '@azure/cosmos': '^4.0.0',
   *   '@azure/identity': '^3.1.0',
   *   'zod': '^3.22.0'
   * }
   * ```
   */
  readonly dependencies?: Record<string, string>;
}
