/**
 * CRUD Function Code Generators
 *
 * @remarks
 * This file is auto-generated by scripts/build-templates.js
 * Each function reads a pre-compiled, minified JavaScript bundle and
 * replaces ATAKORA_* tokens with actual values.
 *
 * The bundles are self-contained with all dependencies included.
 * No npm packages need to be installed at runtime.
 *
 * @packageDocumentation
 */
/**
 * Configuration for crud-create function
 */
export interface GeneratecreateConfig {
    readonly database_name: string;
    readonly container_name: string;
    readonly schema_json: string;
    readonly entity_name_lower: string;
    readonly partition_key: string;
    readonly entity_name: string;
    readonly schemaJson: string;
}
/**
 * Configuration for crud-read function
 */
export interface GeneratereadConfig {
    readonly database_name: string;
    readonly container_name: string;
    readonly entity_name_lower: string;
    readonly entity_name: string;
}
/**
 * Configuration for crud-update function
 */
export interface GenerateupdateConfig {
    readonly database_name: string;
    readonly container_name: string;
    readonly schema_json: string;
    readonly entity_name_lower: string;
    readonly entity_name: string;
    readonly partition_key: string;
    readonly schemaJson: string;
}
/**
 * Configuration for crud-delete function
 */
export interface GeneratedeleteConfig {
    readonly database_name: string;
    readonly container_name: string;
    readonly entity_name_lower: string;
    readonly entity_name: string;
}
/**
 * Configuration for crud-list function
 */
export interface GeneratelistConfig {
    readonly database_name: string;
    readonly container_name: string;
    readonly entity_name_plural_lower: string;
    readonly entity_name_plural: string;
}
/**
 * Generates the crud-create function code
 *
 * @param config - Configuration with entity-specific values
 * @returns Minified, self-contained JavaScript code ready for deployment
 */
export declare function generatecreate(config: GeneratecreateConfig): string;
/**
 * Generates the crud-read function code
 *
 * @param config - Configuration with entity-specific values
 * @returns Minified, self-contained JavaScript code ready for deployment
 */
export declare function generateread(config: GeneratereadConfig): string;
/**
 * Generates the crud-update function code
 *
 * @param config - Configuration with entity-specific values
 * @returns Minified, self-contained JavaScript code ready for deployment
 */
export declare function generateupdate(config: GenerateupdateConfig): string;
/**
 * Generates the crud-delete function code
 *
 * @param config - Configuration with entity-specific values
 * @returns Minified, self-contained JavaScript code ready for deployment
 */
export declare function generatedelete(config: GeneratedeleteConfig): string;
/**
 * Generates the crud-list function code
 *
 * @param config - Configuration with entity-specific values
 * @returns Minified, self-contained JavaScript code ready for deployment
 */
export declare function generatelist(config: GeneratelistConfig): string;
//# sourceMappingURL=index.d.ts.map